import {z} from 'zod';
const stable=z.string().min(1).max(512).refine(value=>value.trim()===value,'id_cannot_have_outer_whitespace');
export const StudentId=stable.brand<'StudentId'>();
export const NativeStudentId=stable.brand<'NativeStudentId'>();
export const EntityId=stable.brand<'EntityId'>();
export const NativeEntityId=stable.brand<'NativeEntityId'>();
export const EvidenceId=stable.brand<'EvidenceId'>();
export const DecisionId=stable.brand<'DecisionId'>();
export const AssignmentId=stable.brand<'AssignmentId'>();
export const SourceId=stable.brand<'SourceId'>();
export const RuleVersion=stable.brand<'RuleVersion'>();
export const Sha256=z.string().regex(/^[a-f0-9]{64}$/).brand<'Sha256'>();
export const Instant=z.string().datetime({offset:true}).brand<'Instant'>();
export type StudentId=z.infer<typeof StudentId>;
export type NativeStudentId=z.infer<typeof NativeStudentId>;
export type EntityId=z.infer<typeof EntityId>;
export type NativeEntityId=z.infer<typeof NativeEntityId>;
export type EvidenceId=z.infer<typeof EvidenceId>;
export type DecisionId=z.infer<typeof DecisionId>;
export type SourceId=z.infer<typeof SourceId>;
export type Sha256=z.infer<typeof Sha256>;
export type Instant=z.infer<typeof Instant>;
export const EventId=stable.brand<'EventId'>();
export type EventId=z.infer<typeof EventId>;
